@startuml "Classes"

top to bottom direction

class Teste {
  + bar foo
}

class Alerta <<abstract>> {
  - number timerHandler
  + Date horario
  + boolean absoluto
  + string descricao
  + cancelar()
  + ajustar(horString)
}
note left of Alerta : Alerta programado.\n\nPossui uma descrição que é\nexibida com a conclusão do\ntimer, na forma de um alerta.

class AlertaRelativo {
  constructor(desc, horExpr)
  + ajustar(horStrExprRel)
  + string: getTempoRestante()
}

class Teste2 {
  - bar baz
}

Alerta <|-- AlertaRelativo
Alerta <|-- AlertaAbsoluto

@enduml
